version: '3.3'
services:
  dogserver:
    build: ./CapstoneApp
    container_name: dogServer_C1
    image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/{REPO_NAME}/{DOG_IMAGE_NAME}:{IMAGE_VERSION}
    ports:
      - 1000:8000
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            capabilities:
#              - gpu
#              - utility # nvidia-smi
#              - compute # CUDA
#              - video
  reactapp:
    build: ./CapstoneApp/reactapp
    container_name: reactApp_C1
    image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/{REPO_NAME}/{REACT_IMAGE_NAME}:{IMAGE_VERSION}
    ports:
       - 3005:3005